name: EllipseApp
description: Ellipse App

publish_to: 'none'

version: 1.0.2+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  ##utils##
  firebase_messaging: ^7.0.3
  firebase_dynamic_links: ^0.6.2
  connectivity: ^2.0.2
  path_provider: ^1.6.27
  web_socket_channel: ^1.2.0
  intl: ^0.16.1
  provider: ^4.3.3
  http: ^0.12.2
  sqflite: ^1.3.2+2
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+14
  share: ^0.6.5+4
  url_launcher: ^5.7.2
  dio: ^3.0.10
  device_info: ^1.0.0
  package_info: ^0.4.3+2
  excel: ^1.1.5
  syncfusion_flutter_pdfviewer: ^18.4.35-beta
  open_file: ^3.0.3
  flutter_local_notifications: ^3.0.2
  flutter_native_timezone: ^1.0.4
  clipboard: ^0.1.2+8

  csv: ^4.1.0
  ##ui##
  carousel_slider: ^2.3.1
  date_time_picker: ^1.1.1
  google_fonts: ^1.1.2
  line_icons: ^0.2.0
  add_2_calendar: ^1.4.0
  big_tip: ^1.1.1+1
  expand_widget: ^1.1.0+1
  fluttertoast: ^7.1.6
  #datetime_picker_formfield: ^1.0.0
  mime: ^0.9.7
  row_collection: ^0.2.4
  sliver_fab: ^1.0.0
  flutter_map: ^0.10.1+1
  auto_size_text: ^2.1.0
  flutter_svg: ^0.19.1
  flutter_swiper: ^1.1.6
  flutter_markdown: ^0.5.2
  feature_discovery: ^0.13.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Gugi
      fonts:
        - asset: assets/fonts/Gugi-Regular.ttf

  assets:
    - assets/svg/event.svg
    - assets/svg/add.svg
    - assets/svg/certificate.svg
    - assets/svg/dashboard.svg
    - assets/icons/
    - assets/