name: ellipseellipse
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.2
  cupertino_icons: ^0.1.3

  connectivity: ^0.4.9
  auto_size_text: ^2.1.0
  carousel_slider: ^2.2.1
  flutter_socket_io: ^0.6.0
  add_2_calendar: ^1.4.0
  big_tip: ^1.1.1
  expand_widget: ^1.0.0+1
  web_socket_channel: ^1.1.0
  fluttertoast: ^7.0.2
  intl: ^0.16.1
  provider: ^4.3.2+1
  image_picker: ^0.6.7+4
  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.10
  http: ^0.12.2
  flutter_swiper: ^1.1.6
  datetime_picker_formfield: ^1.0.0
  mime: ^0.9.7
  flutter_svg: ^0.18.1
  flutter_local_notifications: ^1.4.4+4
  row_collection: ^0.2.4
  search_page: ^1.3.0
  sliver_fab: ^1.0.0
  flutter_map: ^0.10.1+1
  system_setting: ^0.1.3
  flutter_spinkit: ^4.1.2+1
  quick_actions: ^0.4.0+6
  share: ^0.6.4+3
  dio: ^3.0.10
  google_fonts: ^1.1.0
  flutter_web_browser: ^0.11.0
  launch_review: ^2.0.0
  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf

    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf

  assets:
   - assets/icons/
   - assets/
