name: Ellipse
description: Ellipse App

publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  ##utils##
  dio: ^3.0.10
  pdf_flutter: ^1.1.3
  package_info: ^0.4.3
  image_downloader: ^0.20.1
  firebase_admob: ^0.10.0+2
  firebase_messaging: ^7.0.3
  firebase_dynamic_links: ^0.6.0+2
  connectivity: ^0.4.9+5
  path_provider: ^1.6.21
  web_socket_channel: ^1.1.0
  intl: ^0.16.1
  provider: ^4.3.2+2
  http: ^0.12.2
  flutter_web_browser: ^0.12.0
  sqflite: ^1.3.1+1
  shared_preferences: ^0.5.12+2
  image_picker: ^0.6.7+12
  share: ^0.6.5+2
  url_launcher: ^5.7.2
  ##ui##
  custom_navigation_bar: ^0.3.2
  line_icons: ^0.2.0
  shimmer: ^1.1.2
  add_2_calendar: ^1.4.0
  big_tip: ^1.1.1
  expand_widget: ^1.1.0
  fluttertoast: ^7.1.1
  datetime_picker_formfield: ^1.0.0
  mime: ^0.9.7
  row_collection: ^0.2.4
  sliver_fab: ^1.0.0
  flutter_map: ^0.10.1+1
  auto_size_text: ^2.1.0
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.19.0
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
    - family: Gugi
      fonts:
        - asset: assets/fonts/Gugi-Regular.ttf

  assets:
    - assets/icons/
    - assets/
